### ISSUE TITLE
Please add support for AIMP please

### ISSUE THREAD

**Issue by Lescroquetteswow** [rocksdanister/audio-visualizer-wallpaper#13]
It doesn't show the music title / thumbnail with AIMP Music Player

**Comment by rocksdanister** [comment]
https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/main/docs/GSMTC-Support-And-Popular-Apps.md

**Comment by Lescroquetteswow** [comment]
Ty didn't noticed addons
