### ISSUE TITLE
Very high CPU usage

### ISSUE THREAD

**Issue by Rajdave69** [rocksdanister/audio-visualizer-wallpaper#14]
Windows 11 22622.601
Ryzen 7 5800x
RX 6700xt

This wallpaper on both screens is taking 30-40% of my CPU.

**Comment by rocksdanister** [comment]
didnt you report here? https://github.com/rocksdanister/lively/issues/1778#event-9698123419

**Comment by Rajdave69** [comment]
ahh alright thanks
