### ISSUE TITLE
Musicbee support

### ISSUE THREAD

**Issue by L0Lock** [rocksdanister/audio-visualizer-wallpaper#15]
Hi, thanks for the lovely wallpapers! 😊

I'm using [Musicbee](https://getmusicbee.com/) as my audio library manager and player, version [3.5.8447 P](https://getmusicbee.com/forum/index.php?topic=36464.msg209561#msg209561).

Simple Visualizer works perfectly, but Music TV, Media Parallax and Living Room don't work, they all say "offline" or "waiting for media".

Not sure if I'm supposed to set up something somewhere or if it is a matter of software support. Thanks for any help!

**Comment by rocksdanister** [comment]
https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/main/docs/GSMTC-Support-And-Popular-Apps.md

**Comment by L0Lock** [comment]
Hah, I missed a step indeed x) Thanks!
Had to install that plugin: https://github.com/ameer1234567890/mb_MediaControl

Good to note for other MB users: using the install plugin button will return an error, but it's fine. Just reboot Musicbee and the plugin will be enabled and working without anything else to set up.
