### ISSUE TITLE
GSMTC Doesn't Appear to Work

### ISSUE THREAD

**Issue by DBradleyRI** [rocksdanister/audio-visualizer-wallpaper#20]
I downloaded both LivelyWallpaper and Spotify from the Microsoft Store. It seems to me like Spotify's GSMTC isn't functioning because the wallpaper doesn't function when the app is used. However, if I open Spotify in the web browser (Edge), it does work.

I haven't been able to find if there's a way to enable GSMTC on my system manually or within the app. Any advice or additional information I can provide, just let me know.

**Comment by rocksdanister** [comment]
It's a player settings in Spotify:

https://github.com/rocksdanister/lively/wiki/Common-Problems#music-wallpapers-dont-show-albumart-or-track-information

**Comment by DBradleyRI** [comment]
Ahh, so simple, of course!  Thanks for the quick response on this.
