### ISSUE TITLE
Edit the 3D Living Room

### ISSUE THREAD

**Issue by Cheater140** [rocksdanister/audio-visualizer-wallpaper#21]
II tried to modify the room in 3d but when I load it there is an infinite loading screen.
Can you help me please

**Comment by rocksdanister** [comment]
What exactly did you modify?

**Comment by Cheater140** [comment]
Romm.glb

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/audio-visualizer-wallpaper/blob/main/src%2FLiving%20Room%2Findex.html#L239

Code is looking for objects in the model, so if you modify it make sure the same objects exist in the same structure otherwise it will break unless you update the code.

**Comment by Cheater140** [comment]
Ok thanks I will try

**Comment by Cheater140** [comment]
It works thank you very much
