### ISSUE TITLE
No visualization in Screenbox player

### ISSUE THREAD

**Issue by nobef** [rocksdanister/audio-visualizer-wallpaper#24]
I threw the zip files into Apdata/LocalState/Visualizers, selected it through the player, the picture is displayed as a screenshot, but the visualization does not work. What am I doing wrong?
![image](https://github.com/user-attachments/assets/faf77689-9601-4359-b564-c1a1431b29e9)

**Comment by rocksdanister** [comment]
Screenbox needs to add support:
https://github.com/huynhsontung/Screenbox/pull/363

Only music albumart works currently.
