### ISSUE TITLE
Doesn't work with Amazon music

### ISSUE THREAD

**Issue by JoeMusashi9999** [rocksdanister/audio-visualizer-wallpaper#8]
Not sure if this is a windows API issue or not, but the title of the song shows up but not the album cover.
![Screenshot 2023-04-15 144558](https://user-images.githubusercontent.com/63985175/232256260-96b869c9-f3e2-4afe-9d07-dff34fe801f7.png)

**Comment by rocksdanister** [comment]
https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/main/docs/GSMTC-Support-And-Popular-Apps.md
